target 'Honest' do
  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  

  # Pods for Honest

  target 'HonestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HonestUITests' do
       # Pods for testing
  end

end
